### ISSUE TITLE
I like the theme, but i don't know why there is not top bar.

### ISSUE THREAD

**Issue by ghuserac** [kkYrusobad/ObsidianGruv#2]
now, i can't drag obsidian and close obsidian.

**Comment by kkYrusobad** [comment]
I did it only for appearance purposes (also, I don't really use window options.. so there is that). 
If you want a top bar, I've made it possible to toggle it on and off through the theme itself.
In order to toggle the top bar back to where it is supposed to be install the `style settings` community plugin. 
Refer to this [post](https://forum.obsidian.md/t/style-settings-plugin/15901) for more information. Once installed and enabled simply set the theme as `AbsoluteGruv` and navigate to the `style settings` listing in the obsidian settings.

If done correctly, You'll see some settings like this under the `style settings` listing:

![image](https://user-images.githubusercontent.com/55643849/163697655-2c63b73a-c487-4a70-9834-822f82fc5561.png)

Let me know if you face any problems related to this.

**Comment by kkYrusobad** [comment]
Closing this issue for now. Feel free to reopen if you encounter issues related to this.

**Comment by dxps** [comment]
@kkYrusobad I really like your approach to:
1. Hide away the window title bar.
    - For Linux users, moving the window can be done using `Super` (aka Windows key) + `left mouse click` + drag.
2. Hide the File Explorer and Search icons.
    - But still have them available on mouse hover.
      ![image](https://user-images.githubusercontent.com/14140226/178313554-09e0a271-ac4f-42fe-9904-e424dec5ab12.png)
    - I'm using keyboard shortcuts for both panes anyway.
 
Thanks for doing and sharing it! :pray: 

I went further and removed the borders of the left & right panels (in collapse state), plus status bar, so that I could have it even more clean:
![image](https://user-images.githubusercontent.com/14140226/178319721-5d2858bc-0aa4-40ea-8414-8c496adc3e6f.png)

by using:
```shell
❯ cat .obsidian/snippets/wspace_borders.css 


.workspace-ribbon.mod-left.is-collapsed {
    border-right-color: var(--background-secondary-alt);
}

.workspace-ribbon.mod-right.is-collapsed {
    border-left-color: var(--background-secondary-alt);
}

.status-bar {
    border-top-color: var(--background-secondary-alt);
}

❯
```

**Comment by kkYrusobad** [comment]
Thank you for your kind words @dxps. 

I really liked your suggestion to hide the status bar and collapsed panes border. I'll make changes to the theme to have this as default. I will also add a setting button to toggle between borders for the same.

As far as hiding explorer and other icons altogether, I can do that but won't be doing that right now. Look forward to it in the future.

**Comment by dxps** [comment]
Sure, your work deserves them! :blush: 

Regarding the _File Explorer_ and _Search_ icons, I like the current behavior (not sure what you want to change it):
1. By default these are not shown in the expanded sidebar.
   ![image](https://user-images.githubusercontent.com/14140226/178494997-14cfb8b0-7229-4579-b567-bc50301092ac.png)
2. But if you really want to use the mouse, they appear on hover on top region.
   ![image](https://user-images.githubusercontent.com/14140226/178496787-22b74c5a-c8fd-4733-8860-c633607beb36.png)

That's what I meant before about _Hide the File Explorer and Search icons_. So I'm more than happy with the as-is.

**Comment by kkYrusobad** [comment]
Oh okay, I thought you want them not to show even if you hover there. I misunderstood the earlier comment. 
>So I'm more than happy with the as-is

noted. Won't be making any changes now
